### PR TITLE
Feature/tony/trip/user calling taxi

### PR DESCRIPTION
**Pull request by TonyKim9401**
# 해결하려는 문제가 무엇인가요?
* Trip 테이블 상태 변화 정의에 따른 사용자의 택시 이용기록 조회 기능 구현

# 어떻게 해결했나요?
* 다음의 내용을 TDD로 구현
1.사용자가 택시 이용 기록을 조회한다
2.사용자가 택시 이용 기록 조회에 실패한다
3.사용자가 택시 이용 기록을 모두 조회한다

* TDD로 Service 구현을 위해 
1.Trip repository에 메서드 추가
2.TripReader component 계층 추가

* Trip 상태 코드 정의에 따라 결제 요청 및 결제 코드 수정

## Attachment

### CODE REVIEW

**Comment by TonyKim9401** [comment]
### 📝 테스트 커버리지 리포트입니다
|File|Coverage [79.27%]|:x:|
|:-|:-:|:-:|
|[CallingService.kt](https://github.com/KATJ-HH2/katj/blob/d91f3fedbf92fedc6579c0f9acd3f0ffef9d12da/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftrip%2Fservice%2FCallingService.kt)|93.33%|:green_apple:|
|[BillingService.kt](https://github.com/KATJ-HH2/katj/blob/d91f3fedbf92fedc6579c0f9acd3f0ffef9d12da/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftrip%2Fservice%2FBillingService.kt)|91.87%|:green_apple:|
|[TaxiDriver.kt](https://github.com/KATJ-HH2/katj/blob/d91f3fedbf92fedc6579c0f9acd3f0ffef9d12da/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftaxidriver%2Fmodel%2FTaxiDriver.kt)|64.58%|:x:|
|[TripReader.kt](https://github.com/KATJ-HH2/katj/blob/d91f3fedbf92fedc6579c0f9acd3f0ffef9d12da/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftrip%2Fcomponent%2FTripReader.kt)|53.23%|:x:|

|Total Project Coverage|70.82%|:green_apple:|
|:-|:-:|:-:|

**Comment by TonyKim9401** [comment]
### 📝 테스트 커버리지 리포트입니다
|File|Coverage [71.18%]|:x:|
|:-|:-:|:-:|
|[CallingService.kt](https://github.com/KATJ-HH2/katj/blob/c806be7c0b6daa82ae7a76ccd1826ed2eac3a4e9/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftrip%2Fservice%2FCallingService.kt)|93.33%|:green_apple:|
|[BillingService.kt](https://github.com/KATJ-HH2/katj/blob/c806be7c0b6daa82ae7a76ccd1826ed2eac3a4e9/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftrip%2Fservice%2FBillingService.kt)|91.87%|:green_apple:|
|[TaxiDriver.kt](https://github.com/KATJ-HH2/katj/blob/c806be7c0b6daa82ae7a76ccd1826ed2eac3a4e9/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftaxidriver%2Fmodel%2FTaxiDriver.kt)|64.58%|:x:|
|[TripReader.kt](https://github.com/KATJ-HH2/katj/blob/c806be7c0b6daa82ae7a76ccd1826ed2eac3a4e9/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftrip%2Fcomponent%2FTripReader.kt)|53.23%|:x:|
|[TripController.kt](https://github.com/KATJ-HH2/katj/blob/c806be7c0b6daa82ae7a76ccd1826ed2eac3a4e9/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftrip%2Fcontroller%2FTripController.kt)|23.08%|:x:|

|Total Project Coverage|70.52%|:green_apple:|
|:-|:-:|:-:|

**Comment by TonyKim9401** [comment]
### 📝 테스트 커버리지 리포트입니다
|File|Coverage [71.18%]|:x:|
|:-|:-:|:-:|
|[CallingService.kt](https://github.com/KATJ-HH2/katj/blob/da65893b818f204b5e88d1d9253d8b6ce75e1ea4/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftrip%2Fservice%2FCallingService.kt)|93.33%|:green_apple:|
|[BillingService.kt](https://github.com/KATJ-HH2/katj/blob/da65893b818f204b5e88d1d9253d8b6ce75e1ea4/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftrip%2Fservice%2FBillingService.kt)|91.87%|:green_apple:|
|[TaxiDriver.kt](https://github.com/KATJ-HH2/katj/blob/da65893b818f204b5e88d1d9253d8b6ce75e1ea4/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftaxidriver%2Fmodel%2FTaxiDriver.kt)|64.58%|:x:|
|[TripReader.kt](https://github.com/KATJ-HH2/katj/blob/da65893b818f204b5e88d1d9253d8b6ce75e1ea4/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftrip%2Fcomponent%2FTripReader.kt)|53.23%|:x:|
|[TripController.kt](https://github.com/KATJ-HH2/katj/blob/da65893b818f204b5e88d1d9253d8b6ce75e1ea4/src%2Fmain%2Fkotlin%2Fcom%2Fhh2%2Fkatj%2Ftrip%2Fcontroller%2FTripController.kt)|23.08%|:x:|

|Total Project Coverage|70.52%|:green_apple:|
|:-|:-:|:-:|

**Review by jiseongTak — APPROVED** [review]
수고하셨습니다!

**Pull request merged**
